stages:
    - test_std11
    - test_std14
    - test_std17
    - examples
    - benchmarks


.test_template:
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
    script:
        - make tests
        - ${BUILD_DIR}/tests/munkrestest
        - make coverage
    coverage: /^\s*lines.*:\s*\d+.\d+\%/
    only:
        - devel
        - merge_requests


test_job_std11:
    stage:    test_std11
    extends: .test_template
    before_script:
        - !reference [.test_template, before_script]
        - cmake -DCMAKE_BUILD_TYPE=Debug
                -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -Werror -std=c++11"
                ${BUILD_DIR}/..


test_job_std14:
    stage:    test_std14
    extends: .test_template
    before_script:
        - !reference [.test_template, before_script]
        - cmake -DCMAKE_BUILD_TYPE=Debug
                -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -Werror -std=c++14"
                ${BUILD_DIR}/..


test_job_std17:
    stage:    test_std17
    extends: .test_template
    before_script:
        - !reference [.test_template, before_script]
        - cmake -DCMAKE_BUILD_TYPE=Debug
                -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -Werror -std=c++17"
                ${BUILD_DIR}/..


examples_job:
    stage: examples
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake ${BUILD_DIR}/..
    script:
        - make examples
    only:
        - devel
        - merge_requests


benchmarks_job:
    stage: benchmarks
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
    script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRES_CPP_MATRIX_TYPE=Matrix -DMUNKRES_CPP_VALUE_TYPE=long\ double ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRES_CPP_MATRIX_TYPE=matrix_armadillo -DMUNKRES_CPP_VALUE_TYPE=double ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRES_CPP_MATRIX_TYPE=matrix_opencv -DMUNKRES_CPP_VALUE_TYPE=float ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRES_CPP_MATRIX_TYPE=matrix_boost -DMUNKRES_CPP_VALUE_TYPE=long\ unsigned\ int ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRES_CPP_MATRIX_TYPE=matrix_eigen -DMUNKRES_CPP_VALUE_TYPE=unsigned\ int ${BUILD_DIR}/..
        - make benchmarks
    only:
        - devel
        - merge_requests

